### ISSUE TITLE
why the files in lib folder are missing?

### ISSUE THREAD

**Issue by ningliaoyuan** [Justin-Credible/Ionic-TypeScript-Starter#1]

**Comment by ningliaoyuan** [comment]
The issue was solved by updating the angular version from 1.3.15 to 1.3.16.
"resolutions": {
    "angular": "1.3.16"
  }

**Comment by Justin-Credible** [comment]
The lib folder will be populated once you run the `gulp libs` task.

This task will use bower to download the components to the bower_components directory and then populate the lib directory with the needed files.
