### ISSUE TITLE
Use gulp wiredep to include js & css automatically in index.html. 

### ISSUE THREAD

**Issue by surya501** [Justin-Credible/Ionic-TypeScript-Starter#15]
wiredep is a tool to include javascript and css files from bower components automatically and include their dependencies in dependency order between bower tags like below in index.html. 
        
        
        
        

This would make including a bower module as simple single step process as 'bower install stacktrace.js --save' as the index.html would be updated automatically. 

I see that you are using only uri.min.js files as the package includes other files that you do not want. this can be accomplished by using bower overrides as illustrated in https://github.com/taptapship/wiredep#bower-overrides. 

I also see that you are using ionic.bundle.min.js; if we do this this way, we dont have to worry about dependencies. To get a minified file, we need to take all the javascript files and minify, but that is a separate issues.

Going this route would mean that we need to have a 'original' index.html and a index.html with includes in www/ folder. This means copying the original to this location and adding this in gitignore. 

I can submit a pull-request for this; where would you like to move the pristine index.html to?

**Comment by Justin-Credible** [comment]
I like this idea. `Index.source.html` makes sense to me.

**Comment by Justin-Credible** [comment]
Closing this as the wiredep is no longer maintained.
