### ISSUE TITLE
Side menu is available during onboarding in tablet landscape

### ISSUE THREAD

**Issue by Justin-Credible** [Justin-Credible/Ionic-TypeScript-Starter#20]
The side hamburger menu shouldn't be available during the onboarding flow, but it is when a tablet is placed in landscape mode.

**Comment by askrht** [comment]
You learned about the following work around from one of your posts.

```
var $ionicSideMenuDelegate = angular.element(document.body).injector().get("$ionicSideMenuDelegate")
```

Shall I apply this workaround and submit a pull request?

**Comment by Justin-Credible** [comment]
It took a bit more than a call to `canDragAllow()` for the cases where the menu needs to be available after onboarding, but it is now working.

Thanks!

**Comment by askrht** [comment]
This couldn't have been easy. Thank you very much!

**Comment by askrht** [comment]
I left some suggestions in the [code review](https://github.com/Justin-Credible/Ionic-TypeScript-Starter/commit/c09dd5bdd086622040415251798868bf9f8af9ac). Could you please reply to it? Please let me know if it is not such a good idea. Thanks.
