### ISSUE TITLE
Add support for SASS

### ISSUE THREAD

**Issue by Justin-Credible** [Justin-Credible/Ionic-TypeScript-Starter#23]
Switch existing styles to SASS and utilize Ionic's SASS so variables can be more easily changed etc.

**Comment by askrht** [comment]
Submitted a pull request #35 to deliver this enhancement. Travis is clean.

**Comment by askrht** [comment]
Please assign this one to me. I will only add sass this time :-)

**Comment by Justin-Credible** [comment]
Thanks for the offer, but I had already completed this work. It was saved as a stash and just needed some cleanup.

**Comment by askrht** [comment]
Excellent!
