### ISSUE TITLE
Cannot build using VS Code OSX

### ISSUE THREAD

**Issue by kelong** [Justin-Credible/Ionic-TypeScript-Starter#29]
I updated all dependencies to newest version and still has the same errors.
This is my output:

[23:37:10] Using gulpfile ~/Projects/Ionic-TypeScript-Starter/gulpfile.js
[23:37:10] Starting 'ts:vars'...
[23:37:10] Finished 'ts:vars' after 18 ms
[23:37:10] Starting 'ts:src-read-me'...
[23:37:10] Finished 'ts:src-read-me' after 8.88 ms
[23:37:10] Starting 'ts:src'...
[23:37:11] Finished 'ts:src' after 101 ms
[23:37:11] Starting 'ts'...
src/Application.ts(45,26): error TS2503: Cannot find namespace 'Interfaces'.
src/Application.ts(56,34): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(57,34): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(58,34): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(59,35): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(59,73): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(59,111): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(60,36): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(68,73): error TS2339: Property 'ripple' does not exist on type 'Window'.
src/Application.ts(70,47): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(328,31): error TS2305: Module 'Ionic' has no exported member 'IPlatform'.
src/Controllers/BaseController.ts(56,75): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/BaseController.ts(69,74): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/BaseController.ts(82,74): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/BaseController.ts(95,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/BaseController.ts(108,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/BaseController.ts(121,79): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/BaseController.ts(134,79): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/BaseController.ts(147,77): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/CategoryController.ts(30,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Onboarding/OnboardingRegisterController.ts(36,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/RootController.ts(38,75): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/AboutController.ts(26,34): error TS2503: Cannot find namespace 'Interfaces'.
src/Controllers/Settings/AboutController.ts(34,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/CloudSyncController.ts(31,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/CloudSyncController.ts(41,74): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/ConfigurePinController.ts(30,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/DeveloperController.ts(42,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/LogEntryController.ts(29,34): error TS2503: Cannot find namespace 'Interfaces'.
src/Controllers/Settings/LogEntryController.ts(39,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/LogEntryController.ts(74,41): error TS2339: Property 'printStackTrace' does not exist on type 'Window'.
src/Controllers/Settings/LogsController.ts(32,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/SettingsListController.ts(28,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Services/Configuration.ts(22,32): error TS2304: Cannot find name 'BuildVars'.
src/Services/FileUtilities.ts(124,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(129,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(216,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(221,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(293,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(298,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(397,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(402,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(471,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(476,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(545,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(550,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(649,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(654,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(721,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(726,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1011,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1016,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1181,35): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1186,24): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1300,35): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1305,24): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1401,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1406,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1462,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1467,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/HttpInterceptor.ts(99,32): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(99,59): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(174,25): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(177,23): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(204,25): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(221,27): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(241,25): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(254,27): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(297,44): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(365,43): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/Logger.ts(270,45): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/MockPlatformApis.ts(34,34): error TS2304: Cannot find name 'ICordovaToastPlugin'.
src/Services/MockPlatformApis.ts(54,38): error TS2304: Cannot find name 'ICordovaClipboardPlugin'.
src/Services/MockPlatformApis.ts(61,48): error TS2304: Cannot find name 'ICordovaClipboardPlugin'.
src/Services/MockPlatformApis.ts(68,56): error TS2304: Cannot find name 'ICordovaClipboardPlugin'.
src/Services/MockPlatformApis.ts(87,46): error TS2304: Cannot find name 'ICordovaProgressIndicator'.
src/Services/MockPlatformApis.ts(128,40): error TS2304: Cannot find name 'ICordovaCrashlyticsPlugin'.
src/Services/Plugins.ts(45,22): error TS2304: Cannot find name 'ICordovaToastPlugin'.
src/Services/Plugins.ts(46,137): error TS2339: Property 'toast' does not exist on type 'Plugins'.
src/Services/Plugins.ts(47,39): error TS2339: Property 'toast' does not exist on type 'Plugins'.
src/Services/Plugins.ts(57,34): error TS2304: Cannot find name 'ICordovaProgressIndicator'.
src/Services/Plugins.ts(58,81): error TS2339: Property 'ProgressIndicator' does not exist on type 'Window'.
src/Services/Plugins.ts(59,31): error TS2339: Property 'ProgressIndicator' does not exist on type 'Window'.
src/Services/Plugins.ts(69,26): error TS2304: Cannot find name 'ICordovaClipboardPlugin'.
src/Services/Plugins.ts(73,120): error TS2339: Property 'clipboard' does not exist on type 'CordovaPlugins'.
src/Services/Plugins.ts(74,40): error TS2339: Property 'clipboard' does not exist on type 'CordovaPlugins'.
src/Services/Plugins.ts(111,28): error TS2304: Cannot find name 'ICordovaCrashlyticsPlugin'.
src/Services/Plugins.ts(112,92): error TS2339: Property 'crashlytics' does not exist on type 'Navigator'.
src/Services/Plugins.ts(113,34): error TS2339: Property 'crashlytics' does not exist on type 'Navigator'.
src/Services/Utilities.ts(25,32): error TS2304: Cannot find name 'BuildVars'.
src/Services/Utilities.ts(112,38): error TS2339: Property 'ripple' does not exist on type 'Window'.
src/Controllers/Settings/AboutController.ts(26,34): error TS4063: Parameter 'versionInfo' of constructor from exported class has or is using private name 'Interfaces'.
src/Controllers/Settings/LogEntryController.ts(29,34): error TS4063: Parameter 'versionInfo' of constructor from exported class has or is using private name 'Interfaces'.
src/Services/Configuration.ts(22,32): error TS4063: Parameter 'buildVars' of constructor from exported class has or is using private name 'BuildVars'.
src/Services/HttpInterceptor.ts(99,32): error TS4073: Parameter 'config' of public method from exported class has or is using private name 'Interfaces'.
src/Services/HttpInterceptor.ts(99,59): error TS4055: Return type of public method from exported class has or is using private name 'Interfaces'.
src/Services/Logger.ts(270,45): error TS4073: Parameter 'config' of public method from exported class has or is using private name 'Interfaces'.
src/Services/MockPlatformApis.ts(34,34): error TS4055: Return type of public method from exported class has or is using private name 'ICordovaToastPlugin'.
src/Services/MockPlatformApis.ts(54,38): error TS4055: Return type of public method from exported class has or is using private name 'ICordovaClipboardPlugin'.
src/Services/MockPlatformApis.ts(61,48): error TS4055: Return type of public method from exported class has or is using private name 'ICordovaClipboardPlugin'.
src/Services/MockPlatformApis.ts(68,56): error TS4055: Return type of public method from exported class has or is using private name 'ICordovaClipboardPlugin'.
src/Services/MockPlatformApis.ts(87,46): error TS4055: Return type of public method from exported class has or is using private name 'ICordovaProgressIndicator'.
src/Services/MockPlatformApis.ts(128,40): error TS4055: Return type of public method from exported class has or is using private name 'ICordovaCrashlyticsPlugin'.
src/Services/Plugins.ts(45,22): error TS4043: Return type of public property getter from exported class has or is using private name 'ICordovaToastPlugin'.
src/Services/Plugins.ts(57,34): error TS4043: Return type of public property getter from exported class has or is using private name 'ICordovaProgressIndicator'.
src/Services/Plugins.ts(69,26): error TS4043: Return type of public property getter from exported class has or is using private name 'ICordovaClipboardPlugin'.
src/Services/Plugins.ts(111,28): error TS4043: Return type of public property getter from exported class has or is using private name 'ICordovaCrashlyticsPlugin'.
src/Services/Utilities.ts(25,32): error TS4063: Parameter 'buildVars' of constructor from exported class has or is using private name 'BuildVars'.
[23:37:13] 'ts' errored after 2.04 s
[23:37:13] Error: Command failed: /bin/sh -c tsc -p src
    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

**Comment by Justin-Credible** [comment]
When you say that you've updated the dependencies, do you mean you've updated the npm packages to the newest versions? If so, I haven't tried the newer versions myself, so I'm not sure what might break.

From the output it looks like you could be missing the TypeScript definition files. Try running `gulp tsd` and then restart VS Code.
