### ISSUE TITLE
Task git clean:ts does not finish properly

### ISSUE THREAD

**Issue by askrht** [Justin-Credible/Ionic-TypeScript-Starter#39]
Node `del` is not being used correctly in the gulpfile, If you run `gulp clean:ts`, you will not see the `Finished clean:ts` log entry in the console. The problem is incorrect use of Node `del`. Solution is to change how `del` is being used. Change `del(files, cb)` to `del(files).then(...);`. See Node [del](https://www.npmjs.com/package/del).

**Comment by Justin-Credible** [comment]
Fixed via edff518fed3775902e30ea7e229602c059464786
