### ISSUE TITLE
Enhancement: Transform empty Categories into useful Features.

### ISSUE THREAD

**Issue by askrht** [Justin-Credible/Ionic-TypeScript-Starter#42]
Angular 2.0 follows a component design and John Papa's Angular [style guide](https://github.com/johnpapa/angular-styleguide#style-y163) also favors a modular approach. To avoid a major re-work, when we move to Angular 2, I recommend that we transform existing Categories into Features. Here's an outline of the proposed changes:
1. Each Feature has it's own directory which contains all it's files.
2. Each Feature contains sample code to demonstrate a functionality which is required for most mobile apps. For instance, each useful Cordova plugin could be a separate Feature to show how it is used. Here are a few:
   - [cordova-plugin-camera](https://www.npmjs.com/package/cordova-plugin-camera)
   - [cordova-plugin-file-transfer](https://www.npmjs.com/package/cordova-plugin-file-transfer)
   - File viewer
   - [phonegap-plugin-push](https://www.npmjs.com/package/phonegap-plugin-push)
   - [cordova-plugin-indexeddb-async](https://www.npmjs.com/package/cordova-plugin-indexeddb-async)
   - [phonegap-plugin-barcodescanner](https://www.npmjs.com/package/phonegap-plugin-barcodescanner)
3. It lowers the learning curve for adding a new Feature. Contributors will find it easier add new demo Features, once a pattern has been established.
4. Maintainability will not go down as more Features are added.
5. Update README.md with instructions on how to remove a Feature that is not required by your app.
6. These changes should be tested in a separate branch.

**Comment by askrht** [comment]
Please let me have your thoughts on this. Thanks.

**Comment by Justin-Credible** [comment]
I think this is beyond the scope of a starter project. I would like to avoid as many dependencies as possible.
