### ISSUE TITLE
Enhancement: Provide an example of OAuth2

### ISSUE THREAD

**Issue by askrht** [Justin-Credible/Ionic-TypeScript-Starter#46]
1. Users have too many online accounts and they shouldn't need to create another one, if it can be avoided. Current template includes a very capable `HttpInterceptor` for basic authentication, but I think it would be hard for many, to extend the template to do OAuth2, when they are just getting started. I propose including code for Google's OAuth2 as an example. Google's `ClientID` could be read from `BuildVars`.
2. I also suggest that you open a new **development** branch to accept contributions. This will give you a chance to work on the contribution, add your improvements and merge it to the master after you have refined it.

**Comment by Justin-Credible** [comment]
I think this is beyond the scope of this starter project.
