### ISSUE TITLE
npm install hangs

### ISSUE THREAD

**Issue by fabean** [Justin-Credible/Ionic-TypeScript-Starter#51]
I know it's not your fault that npm wants to suck, but I only have this issue on your project.

Using Node 4.2.4, when I clone down the project and run `npm install` it will just hang forever. I've tried running in verbose as I've read other places this helps.

Everyone on my team has experienced this issue with this repo, do you have any suggestions or ever run into this issue yourself?

**Comment by fabean** [comment]
For now I ended up running `npm config set registry http://registry.npmjs.org/` and it made it better. But I had to manually `npm install` a couple things at a time.

**Comment by Justin-Credible** [comment]
Hmm, I haven't encountered this on 4.2.2 or 4.2.4. I develop on Mac OS 10.11.1 as well as Windows 10, and `npm install` completes without any errors.

Are you on Windows? I know Windows often have issues with the length of paths used by node modules. Perhaps you could try using a shorter path for your root clone location.
