### ISSUE TITLE
Error after gulp init

### ISSUE THREAD

**Issue by mjsorribas** [Justin-Credible/Ionic-TypeScript-Starter#55]
When i try run  # gulp init  
this error appears:
# Error: Registry returned 404 for GET on https://registry.npmjs.org/com.verso.cordova.clipboard

[16:59:25] 'plugins' errored after 1.1 min
[16:59:25] Error: Command failed: /bin/sh -c cordova plugin add com.verso.cordova.clipboard@0.1.0
Error: Failed to fetch plugin com.verso.cordova.clipboard@0.1.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.verso.cordova.clipboard
this purl is empty.

and  this error appears when i run # ionic serve:  Uncaught ReferenceError: JustinCredible is not defined, http://localhost:8100/js/boot1.js, Line: 17.

**Comment by Justin-Credible** [comment]
I was unable to reproduce this--it looks like a problem with npm.

Please verify that you've added `./node_modules/.bin` before running `gulp plugins`.

**Comment by mjsorribas** [comment]
Hi, the problem is the  com.verso.cordova.clipboard , now I remove it from package.json and then I install it using the command 
` cordova plugin add https://github.com/VersoSolutions/CordovaClipboard.git`
the I run again gulp and it's works.

**Comment by Justin-Credible** [comment]
It looks like the plugin ID on the npm registry was different from the ID used on the Cordova plugin registry. Not sure why this was an issue for you and not for me (for me it fell back to the Cordova registry gracefully).

It should work for you now as I've updated to the new plugin ID `cordova-universal-clipboard`.
