### ISSUE TITLE
gulp package-web generates an empty app.bundle.lib.js

### ISSUE THREAD

**Issue by askrht** [Justin-Credible/Ionic-TypeScript-Starter#65]
Here is the environment:

```
ionic info

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v4.4.0
```

Steps to reproduce:

```
git clone https://github.com/Justin-Credible/Ionic-TypeScript-Starter.git
cd Ionic-TypeScript-Starter/
npm install
gulp init
gulp config --prep web --scheme release

gulp package-web
[14:35:28] Info: Moving bundled lib to build/web/lib/app.bundle.lib.js
shell.js: internal error
Error: ENOENT: no such file or directory, rename 'build/web/resources-temp/app.bundle.lib.js' -> 'build/web/lib/app.bundle.lib.js'
    at Error (native)
    at Object.fs.renameSync (fs.js:681:18)

## Execute it again
gulp package-web
[14:37:42] Info: Bundling css, lib, and js directories to build/web/resources-temp
cat: no such file or directory: build/web/lib/uri.js/uri.min.js

echo $?
0

cat build/web/lib/app.bundle.lib.js && echo
null
```

**Comment by askrht** [comment]
uri.js has been renamed to URI.js, sigh! To avoid changes al lover the place and to make it easier on us when they revert, we can simply modify bower.json. Here's the patch:

```
diff --git a/bower.json b/bower.json
index 6821771..f265a1d 100644
--- a/bower.json
+++ b/bower.json
@@ -14,7 +14,11 @@
     "sources": {
       "lodash": "bower_components/lodash/lodash.min.js",
       "moment": "bower_components/moment/min/moment.min.js",
-      "uri.js": "bower_components/uri.js/src/uri.min.js",
+      "uri.js": {
+        "mapping": [
+          { "bower_components/uri.js/src/URI.min.js": "uri.min.js" }
+        ]
+      },
       "ionic": {
         "mapping": [
           { "bower_components/ionic/release/js/ionic.bundle.min.js": "js/ionic.bundle.min.js" },
```

I you like, I can submit a pull request

**Comment by Justin-Credible** [comment]
Thanks for the heads up! I looked into this further and it was due to two problems:

1. The tasks that created the `build/chrome` and `build/web` directories weren't creating the path recursively, so if the `build` directory didn't exist, the command would fail.
2. The `www` directory was being copied into the output directory as a _sub-directory_ instead of having its contents copied.

This should be fixed with the pull request I just merged.

**Comment by askrht** [comment]
Thanks for a super fast fix.

I also notice that the `--prep release` flag is not honored either by the package-web or by package-chrome. These tasks do not minify `bundle.js` despite executing `gulp config --scheme release` before them.  Is it possible you could fix that as well?

**Comment by askrht** [comment]
I found a workaround. You have to execute the command given below **twice** because they do not run in sequence.

```
gulp ts package-web --scheme release
```
