### ISSUE TITLE
Issues with CORS when interfacing with Express Server

### ISSUE THREAD

**Issue by jonnycraze** [Justin-Credible/Ionic-TypeScript-Starter#69]
I'm having some issues with this and i'm not sure if there's something inside the app that is hindering me requests.

I have removed all of the security policy meta data in hopes of solving the issue.

on my first POST everything works, and the session is seemingly created on the server, however when accessing that session through another GET request (which is authenticated through passportJS) it cannot find my session.

I've gone back and forth on if this is the server or the client as the culprit, I think it is something in the NG App because when I do these actions from Postman, the session is maintained, and interacting with the endpoints that require authentication is not a problem.

I've been racking my brain on this for more hours than I'd like to admit, if you've run into this with this project could you let me know if you were able to solve it, or something I may have missed.

Thanks

**Comment by Justin-Credible** [comment]
How are you running your app?

If you are using a browser with `ionic serve` then your HTTP requests will be blocked by CORS. You need to disable the CORS check. More details [here](http://justin-credible.github.io/Ionic-TypeScript-Starter/development-tips/#developing-with-chrome), but if you are using Chrome you can use this:

```
# OS X
$ open -a "Google Chrome.app" --ignore-certificate-errors --disable-web-security --user-data-dir=/tmp/ChromeDev

# Windows
> chrome.exe --ignore-certificate-errors --disable-web-security --user-data-dir=C:\tmp\ChromeDev
```

Then you can use the network tab of the browser's developer tools to examine the XHRs.

**Comment by jonnycraze** [comment]
Hi Justin, 

Thanks for the quick response I appreciate it.
I'm using 'ionic serve' and viewing in chrome on windows.

I'll try your suggestion and get back shortly

**Comment by jonnycraze** [comment]
Is there a way for me to run this as a webapp locally (without cordova) to bypass the CORS issues?

**Comment by Justin-Credible** [comment]
Yeah, that would be running `ionic serve` and then launching Chrome with the above command line switches. Did that not work for you?

**Comment by jonnycraze** [comment]
It did indeed work, I'm just wondering if it's possible for me to deploy this as a webapp. and how to do that. is it simply `gulp config --prep web` ?

If so, do ionic plugins such as geolocation still work in this mode?

Thanks for your help Justin, much appreciated.

**Comment by Justin-Credible** [comment]
Ah sorry, I missed that part. Yeah, you can use the `package-web` task:

http://justin-credible.github.io/Ionic-TypeScript-Starter/gulp-tasks/#gulp-package-web

None of the native code Cordova plugins will be available on the web of course. You'll be limited to the browser's JavaScript APIs for geolocation etc.

If your code base will be shared between a Cordova app and a web app, then you can use `Utilities.isCordova` to check to see which container you are running in and provide an alternate code path for when you do not have native plugins available.

**Comment by jonnycraze** [comment]
Awesome, thanks again for your help. I'm new to building in Cordova and thinking both about native and web.

**Comment by jonnycraze** [comment]
Closing issue as the answers above resolved my questions and issues.

**Comment by jonnycraze** [comment]
@Justin-Credible I'm wondering if i'm missing something here, I am now packaging for web, and I am still getting errors regarding interfacing with an external api.

When i run the web app that is bundled through `gulp package-web` it fires up and is functional but will not hold a session, it seems. When I open in chrome with extra security disabled it does work.
