### ISSUE TITLE
CORS with package-web

### ISSUE THREAD

**Issue by jonnycraze** [Justin-Credible/Ionic-TypeScript-Starter#70]
Hey Justin, I'm wondering if i'm missing something here, I am now packaging for web, and I am still getting errors regarding interfacing with an external api.

When i run the web app that is bundled through gulp package-web it fires up and is functional but will not hold a session, it seems. When I open in chrome with extra security disabled it does work.

Is there something in the config that could be tripping it up? I can send you a link to see it in action if needed.

**Comment by Justin-Credible** [comment]
Have you checked the Chrome developer tools console and/or network tab? Those areas usually give clues as to the issue.

**Comment by Justin-Credible** [comment]
I just tested this, and didn't experience any problems.

You may need to enable CORS on your server if you are serving the Ionic app on a different domain than the API you are trying to call.

https://enable-cors.org/server.html has some great information on setting up CORS on your server.
