### ISSUE TITLE
Build the project using Visual Studio

### ISSUE THREAD

**Issue by Yaojian** [Justin-Credible/Ionic-TypeScript-Starter#8]
Is it possible to add a VS project so we can build this project with either vs or command line interface?

The two project `Ionic-TypeScript-Starter` and `Ionic-TypeScript-MDHA-Starter` can be merged into one project that supports building both with either VS or CLI.

Thanks for your great job.

**Comment by Justin-Credible** [comment]
Definitely! I'm working on this as it will reduce the maintenance burden for me. :)

**Comment by Yaojian** [comment]
Just a note: The plugin `org.pbernasconi.progressindicator` has a `demo` subdirectory that is too long for visual studio. Would you change the plugin to the same as in Ionic-TypeScript-MDHA-Starter?

**Comment by Justin-Credible** [comment]
Yep; this was done in #11

**Comment by Yaojian** [comment]
I forked this project and tried to create VS project file. Everything seems ok except VS always in high CPU occupation after opening the project file. Any ideas?

http://stackoverflow.com/questions/31824892/cpu-high-after-visual-studio-2015-rtm-openning-an-cordova-project

**Comment by Yaojian** [comment]
Nothing is wrong, The high CPU is caused by Resharper solution wide analysis. 
Sorry for my bother.

**Comment by Justin-Credible** [comment]
I've decided not to pursue this for the time being. There are too many differences between using a gulpfile and Visual Studio's project template. It is kind of a black box and some of the configuration isn't accessible. I believe this would lead to to many compromises if I were to get it working for both.
