### ISSUE TITLE
gulp tsd:tests deletes custom typings

### ISSUE THREAD

**Issue by surya501** [Justin-Credible/Ionic-TypeScript-Starter#9]
running gulp with no parameters deletes files in the typings/custom directory and hence the 'gulp ts' task results in a lot of errors starting with error TS2503: Cannot find namespace 'Interfaces'.;

checking out the deleted files, manually adding the file references to the tsd.d.ts and then running 'gulp ts' alone fixes these issues.

I can try fixing these and submitting a pull request, but would like some guidance on how to do this as I am new to typescript. ( if it matters, I am running this on ubuntu)

**Comment by Justin-Credible** [comment]
Hmm, I can't reproduce this on OSX 10.10.3 or Windows 10 (sorry, I don't have a *nix box to test on). Perhaps you can provide some more information? Below are the exact console commands I used. I didn't encounter any errors (from `gulp ts`, `gulp`, or building in VSCode) and was able to run using `ionic serve` and `ionic emulate ios`.

One thing you might try is re-running `gulp tsd`. I know the GitHub API is rate limited, and sometimes this can prevent `tsd` from pulling down all the TypeScript definition files, which will then result in compile errors.

Hope this helps!

    $ node --version
    v0.10.38

    $ npm --version
    2.11.2

    $ tsc --version
    message TS6029: Version 1.5.0-beta

    $ git clone git@github.com:Justin-Credible/Ionic-TypeScript-Starter.git testing_issue_#9
    $ cd testing_issue_#9
    $ npm install
    $ gulp
    $ ls typings/custom
        CordovaPlugins.d.ts DataTypes.d.ts      Extensions.d.ts     Interfaces.d.ts    ionic.d.ts

**Comment by surya501** [comment]
My installed version for node, npm and typescript is as follows:
$ node --version
v0.12.7
$ npm --version
2.11.3
$ tsc --version
message TS6029: Version 1.5.3

When I run gulp, I get the following in the middle of the execution:
<<----- deleted for relevancy---->>
[00:25:16] Starting 'tsd:tests'...
-> running reinstall
>> written zero files
>> removed:
    - custom/CordovaPlugins.d.ts
    - custom/DataTypes.d.ts
    - custom/Extensions.d.ts
    - custom/Interfaces.d.ts
    - custom/ionic.d.ts
<<----- deleted for relevancy---->>

**Comment by Justin-Credible** [comment]
I just made a change that ensures `tsd:app` finishes executing before `tsd:tests` begins in commit 42681485d41c90becdf870094279eea331774f47. Maybe it will help.

The only other major difference I can see is that I'm using TypeScript 1.5.0-beta and you're on 1.5.3.

**Comment by surya501** [comment]
I narrowed down the error to "tsd reinstall" part of the script. If I run tsd reinstall and do a git status, I can see that all the custom typing files are deleted. If I then check it out and then run the  tsd rebundle, everything runs fine.

On a different note, I am interested in helping out. Can I help you with some how to use documentation for creating an ionic project? Or are there  better places to help out?

**Comment by Justin-Credible** [comment]
Hmm, I still can't reproduce this, even using the `tsd reinstall` command directly.

The only thing I can think of is that the version of `tsd` you are using my be different than the one that is packed with the starter. I'm using 0.6.1. Can you check your version? Are you using `./node_modules/.bin` in your path (to ensure you are using the `tsd` that is in the starter project)?
